package Com;
// Generated Jan 12, 2019 5:52:10 AM by Hibernate Tools 4.3.1



/**
 * NewCar generated by hbm2java
 */
public class NewCar  implements java.io.Serializable {


     private long id;
     private String name;
     private String model;
     private String type;
     private Long price;
     private Long year;
     private Long hp;
     private Long cylinder;
     private String gearbox;
     private byte[] image;

    public NewCar() {
    }

	
    public NewCar(long id) {
        this.id = id;
    }
    public NewCar(long id, String name, String model, String type, Long price, Long year, Long hp, Long cylinder, String gearbox, byte[] image) {
       this.id = id;
       this.name = name;
       this.model = model;
       this.type = type;
       this.price = price;
       this.year = year;
       this.hp = hp;
       this.cylinder = cylinder;
       this.gearbox = gearbox;
       this.image = image;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }
    public Long getHp() {
        return this.hp;
    }
    
    public void setHp(Long hp) {
        this.hp = hp;
    }
    public Long getCylinder() {
        return this.cylinder;
    }
    
    public void setCylinder(Long cylinder) {
        this.cylinder = cylinder;
    }
    public String getGearbox() {
        return this.gearbox;
    }
    
    public void setGearbox(String gearbox) {
        this.gearbox = gearbox;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


