package Com;
// Generated Jan 12, 2019 5:52:10 AM by Hibernate Tools 4.3.1



/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private long id;
     private String name;

    public Privilege() {
    }

	
    public Privilege(long id) {
        this.id = id;
    }
    public Privilege(long id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


