package Com;
// Generated Jan 12, 2019 5:52:10 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * UsedCar generated by hbm2java
 */
public class UsedCar  implements java.io.Serializable {


     private long id;
     private Users users;
     private String name;
     private String model;
     private String type;
     private Long price;
     private Long year;
     private Long hp;
     private Long cylinder;
     private String gearbox;
     private BigDecimal km;
     private String detials;
     private byte[] image;

    public UsedCar() {
    }

	
    public UsedCar(long id) {
        this.id = id;
    }
    public UsedCar(long id, Users users, String name, String model, String type, Long price, Long year, Long hp, Long cylinder, String gearbox, BigDecimal km, String detials, byte[] image) {
       this.id = id;
       this.users = users;
       this.name = name;
       this.model = model;
       this.type = type;
       this.price = price;
       this.year = year;
       this.hp = hp;
       this.cylinder = cylinder;
       this.gearbox = gearbox;
       this.km = km;
       this.detials = detials;
       this.image = image;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }
    public Long getHp() {
        return this.hp;
    }
    
    public void setHp(Long hp) {
        this.hp = hp;
    }
    public Long getCylinder() {
        return this.cylinder;
    }
    
    public void setCylinder(Long cylinder) {
        this.cylinder = cylinder;
    }
    public String getGearbox() {
        return this.gearbox;
    }
    
    public void setGearbox(String gearbox) {
        this.gearbox = gearbox;
    }
    public BigDecimal getKm() {
        return this.km;
    }
    
    public void setKm(BigDecimal km) {
        this.km = km;
    }
    public String getDetials() {
        return this.detials;
    }
    
    public void setDetials(String detials) {
        this.detials = detials;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


