package Com;
// Generated Jan 12, 2019 5:52:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long id;
     private String fname;
     private String lname;
     private String email;
     private String password;
     private String gender;
     private Long privilegeId;
     private Set<Blog> blogs = new HashSet<Blog>(0);
     private Set<UsedCar> usedCars = new HashSet<UsedCar>(0);
     private Set<UsedMoto> usedMotos = new HashSet<UsedMoto>(0);

    public Users() {
    }

	
    public Users(long id) {
        this.id = id;
    }
    public Users(long id, String fname, String lname, String email, String password, String gender, Long privilegeId, Set<Blog> blogs, Set<UsedCar> usedCars, Set<UsedMoto> usedMotos) {
       this.id = id;
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.password = password;
       this.gender = gender;
       this.privilegeId = privilegeId;
       this.blogs = blogs;
       this.usedCars = usedCars;
       this.usedMotos = usedMotos;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Long getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
    public Set<Blog> getBlogs() {
        return this.blogs;
    }
    
    public void setBlogs(Set<Blog> blogs) {
        this.blogs = blogs;
    }
    public Set<UsedCar> getUsedCars() {
        return this.usedCars;
    }
    
    public void setUsedCars(Set<UsedCar> usedCars) {
        this.usedCars = usedCars;
    }
    public Set<UsedMoto> getUsedMotos() {
        return this.usedMotos;
    }
    
    public void setUsedMotos(Set<UsedMoto> usedMotos) {
        this.usedMotos = usedMotos;
    }




}


